<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ronak" ignored="0" name="Default test" tests="14" failures="1" timestamp="16 Oct 2019 16:25:12 GMT" time="48.447" errors="0">
  <testcase name="verifyURl" time="10.592" classname="Testcases.apptest"/>
  <testcase name="verifytitle" time="0.111" classname="Testcases.apptest"/>
  <testcase name="verifyloginbuttonText" time="0.095" classname="Testcases.apptest"/>
  <testcase name="verifyloginheadingText" time="0.104" classname="Testcases.apptest"/>
  <testcase name="verifyforgotpasswordtext" time="2.522" classname="Testcases.apptest"/>
  <testcase name="verifyforgotpassheadingtext" time="0.021" classname="Testcases.apptest"/>
  <testcase name="verifyforgotpassusernamelabel" time="0.062" classname="Testcases.apptest"/>
  <testcase name="verifyresetpasswordbuttontext" time="3.898" classname="Testcases.apptest"/>
  <testcase name="verifyloginwithvalidusername" time="2.006" classname="Testcases.apptest"/>
  <testcase name="verifylogiwithvalidpassword" time="1.699" classname="Testcases.apptest"/>
  <testcase name="verifyloginwithwrongusernameandpassword" time="1.634" classname="Testcases.apptest"/>
  <testcase name="verifyloginwithblank" time="0.255" classname="Testcases.apptest"/>
  <testcase name="verifylogin" time="7.026" classname="Testcases.apptest"/>
  <testcase name="addadmin" time="10.207" classname="Testcases.apptest">
    <failure type="java.lang.AssertionError" message="expected [Already exist] but found []">
      <![CDATA[java.lang.AssertionError: expected [Already exist] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.techbeamers.base.BaseTest.adduser(BaseTest.java:141)
at Testcases.apptest.addadmin(apptest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addadmin -->
</testsuite> <!-- Default test -->
